# (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

# pyre-strict

from collections.abc import AsyncGenerator, Callable, Coroutine, Generator
from typing import TypeVar

FuncAny = Callable[..., object]

TDeoptGenYield = TypeVar("TDeoptGenYield")
TDeoptGenSend = TypeVar("TDeoptGenSend")
TDeoptGenReturn = TypeVar("TDeoptGenReturn")

def _deopt_gen(
    gen: (
        Generator[TDeoptGenYield, TDeoptGenSend, TDeoptGenReturn]
        | AsyncGenerator[TDeoptGenYield, TDeoptGenSend]
        | Coroutine[TDeoptGenYield, TDeoptGenSend, TDeoptGenReturn]
    ),
) -> bool: ...
def append_jit_list(entry: str) -> None: ...
def auto() -> None: ...
def clear_runtime_stats() -> None: ...
def compile_after_n_calls(calls: int) -> None: ...
def count_interpreted_calls(func: FuncAny) -> int: ...
def disable(deopt_all: bool = False) -> None: ...
def disable(deopt_all: bool = False) -> None: ...
def disable_emit_type_annotation_guards() -> None: ...
def disable_hir_inliner() -> None: ...
def disable_specialized_opcodes() -> None: ...
def enable() -> None: ...
def enable_emit_type_annotation_guards() -> None: ...
def enable_hir_inliner() -> None: ...
def enable_specialized_opcodes() -> None: ...
def force_compile(func: FuncAny) -> bool: ...
def force_uncompile(func: FuncAny) -> bool: ...
def get_allocator_stats() -> dict[str, int]: ...
def get_and_clear_inline_cache_stats() -> dict[str, object]: ...
def get_and_clear_runtime_stats() -> dict[str, object]: ...
def get_compilation_time() -> int: ...
def get_compile_after_n_calls() -> int | None: ...
def get_compiled_functions() -> list[FuncAny]: ...
def get_compiled_size(func: FuncAny) -> int: ...
def get_compiled_spill_stack_size(func: FuncAny) -> int: ...
def get_compiled_stack_size(func: FuncAny) -> int: ...
def get_function_compilation_time(func: FuncAny) -> int: ...
def get_function_hir_opcode_counts(func: FuncAny) -> dict[str, int] | None: ...
def get_inlined_functions_stats(func: FuncAny) -> dict[str, object]: ...
def get_jit_list() -> tuple[dict[str, set[str]], dict[str, dict[str, set[int]]]]: ...
def get_num_inlined_functions(func: FuncAny) -> int: ...
def is_enabled() -> bool: ...
def is_hir_inliner_enabled() -> bool: ...
def is_inline_cache_stats_collection_enabled() -> bool: ...
def is_jit_compiled(func: FuncAny) -> bool: ...
def jit_suppress(func: FuncAny) -> FuncAny: ...
def jit_unsuppress(func: FuncAny) -> FuncAny: ...
def lazy_compile(func: FuncAny) -> bool: ...
def mlock_profiler_dependencies() -> None: ...
def multithreaded_compile_test() -> None: ...
def page_in_profiler_dependencies() -> list[str]: ...
def precompile_all(workers: int = 0) -> bool: ...
def read_jit_list(path: str) -> None: ...
def set_max_code_size(max_code_size: int) -> None: ...
