[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "cinderx"
description = "High-performance Python runtime extension"
requires-python = "== 3.12.*"
version = "0.1"
