# Copyright (c) Meta Platforms, Inc. and affiliates.
# flake8: noqa

from .test_annotated import AnnotatedTests
from .test_array import ArrayTests
from .test_asyncs import AsyncTests
from .test_augassign import AugAssignTests
from .test_binop import BinopTests
from .test_cached_property import CachedPropertyTests
from .test_checked_dict import CheckedDictTests
from .test_checked_list import CheckedListTests
from .test_class_decorator import ClassDecoratorTests
from .test_classmethod import ClassMethodTests
from .test_compile import StaticCompilationTests
from .test_context_decorator import ContextDecoratorTests
from .test_crange import CRangeTests
from .test_dataclass import DataclassTests
from .test_decl_visitor import DeclarationVisitorTests
from .test_dependencies import DependencyTrackingTests
from .test_double import DoubleTests
from .test_dynamic_return import DynamicReturnTests
from .test_elide_type_checks import ElideTypeChecksTests
from .test_enum import StaticEnumTests
from .test_fields import StaticFieldTests
from .test_final import FinalTests
from .test_fstring import FStringTests
from .test_implicit_none_return import ImplicitNoneReturnTests
from .test_imports import ImportTests
from .test_inference import InferenceTests
from .test_invoke import InvokeTests
from .test_lint import LintTests
from .test_literals import LiteralsTests
from .test_match import MatchTests
from .test_module import ModuleTests
from .test_native import NativeDecoratorTests
from .test_non_static_inheritance import NonStaticInheritanceTests
from .test_obj_creation import StaticObjCreationTests
from .test_overrides import OverridesTests
from .test_patch import StaticPatchTests
from .test_perf_lint import PerfLintTests
from .test_primitives import PrimitivesTests
from .test_property import PropertyTests
from .test_protocol import ProtocolTests
from .test_refine_fields import RefineFieldsTests
from .test_reflection import ReflectionTests
from .test_return_cast_insertion import ReturnCastInsertionTests
from .test_runtime import StaticRuntimeTests
from .test_sequence import SequenceTests
from .test_slots_with_default import SlotsWithDefaultTests
from .test_staticarray import StaticArrayTests
from .test_staticmod import StaticModuleTests
from .test_subclass import SubclassTests
from .test_super import SuperTests
from .test_sys_hexversion import SysHexVersionTests
from .test_top_level import TopLevelTests
from .test_typed_dict import TypedDictTests
from .test_union import UnionCompilationTests
from .test_unknown_names import UnknownNameTests
from .test_variadic_arg import VariadicArgTests
from .test_walrus_operator import WalrusOperatorTests
