
// Copyright (c) Meta Platforms, Inc. and affiliates.

// 3.14 has a simple file that just defines the relavant ids:

#include "opcode.h"

// 0x200 to make sure we don't collide with pseudo instructions
#define EXTENDED_OPCODE_FLAG 0x200


#define INVOKE_METHOD (1 | EXTENDED_OPCODE_FLAG)
#define LOAD_FIELD (2 | EXTENDED_OPCODE_FLAG)
#define LOAD_OBJ_FIELD (5 | EXTENDED_OPCODE_FLAG)
#define LOAD_PRIMITIVE_FIELD (6 | EXTENDED_OPCODE_FLAG)
#define STORE_FIELD (7 | EXTENDED_OPCODE_FLAG)
#define STORE_OBJ_FIELD (8 | EXTENDED_OPCODE_FLAG)
#define STORE_PRIMITIVE_FIELD (9 | EXTENDED_OPCODE_FLAG)
#define BUILD_CHECKED_LIST (10 | EXTENDED_OPCODE_FLAG)
#define BUILD_CHECKED_LIST_CACHED (11 | EXTENDED_OPCODE_FLAG)
#define LOAD_TYPE (12 | EXTENDED_OPCODE_FLAG)
#define CAST (13 | EXTENDED_OPCODE_FLAG)
#define CAST_CACHED (14 | EXTENDED_OPCODE_FLAG)
#define LOAD_LOCAL (15 | EXTENDED_OPCODE_FLAG)
#define STORE_LOCAL (16 | EXTENDED_OPCODE_FLAG)
#define STORE_LOCAL_CACHED (17 | EXTENDED_OPCODE_FLAG)
#define PRIMITIVE_BOX (18 | EXTENDED_OPCODE_FLAG)
#define POP_JUMP_IF_ZERO (99 | EXTENDED_OPCODE_FLAG)
#define POP_JUMP_IF_NONZERO (102 | EXTENDED_OPCODE_FLAG)
#define PRIMITIVE_UNBOX (19 | EXTENDED_OPCODE_FLAG)
#define PRIMITIVE_BINARY_OP (20 | EXTENDED_OPCODE_FLAG)
#define PRIMITIVE_UNARY_OP (21 | EXTENDED_OPCODE_FLAG)
#define PRIMITIVE_COMPARE_OP (22 | EXTENDED_OPCODE_FLAG)
#define LOAD_ITERABLE_ARG (23 | EXTENDED_OPCODE_FLAG)
#define LOAD_MAPPING_ARG (24 | EXTENDED_OPCODE_FLAG)
#define INVOKE_FUNCTION (25 | EXTENDED_OPCODE_FLAG)
#define INVOKE_FUNCTION_CACHED (26 | EXTENDED_OPCODE_FLAG)
#define INVOKE_INDIRECT_CACHED (27 | EXTENDED_OPCODE_FLAG)
#define FAST_LEN (28 | EXTENDED_OPCODE_FLAG)
#define CONVERT_PRIMITIVE (29 | EXTENDED_OPCODE_FLAG)
#define INVOKE_NATIVE (30 | EXTENDED_OPCODE_FLAG)
#define LOAD_CLASS (31 | EXTENDED_OPCODE_FLAG)
#define BUILD_CHECKED_MAP (32 | EXTENDED_OPCODE_FLAG)
#define BUILD_CHECKED_MAP_CACHED (33 | EXTENDED_OPCODE_FLAG)
#define SEQUENCE_GET (34 | EXTENDED_OPCODE_FLAG)
#define SEQUENCE_SET (35 | EXTENDED_OPCODE_FLAG)
#define LIST_DEL (38 | EXTENDED_OPCODE_FLAG)
#define REFINE_TYPE (39 | EXTENDED_OPCODE_FLAG)
#define PRIMITIVE_LOAD_CONST (40 | EXTENDED_OPCODE_FLAG)
#define RETURN_PRIMITIVE (41 | EXTENDED_OPCODE_FLAG)
#define TP_ALLOC (43 | EXTENDED_OPCODE_FLAG)
#define TP_ALLOC_CACHED (44 | EXTENDED_OPCODE_FLAG)
#define LOAD_METHOD_STATIC (45 | EXTENDED_OPCODE_FLAG)
#define LOAD_METHOD_STATIC_CACHED (46 | EXTENDED_OPCODE_FLAG)
