#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.

"""Turn classify_cpython_tests.py output into a Buck test partition."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

BZL_HEADER = '''\
# @generated by cinderx/TestScripts/gen_cpython_test_defs.py
# Regenerate with cinderx/TestScripts/regen_cpython_test_partition.sh
#
# TIER1_TESTS run as python_unittest targets in cinderx/CPythonTests, one shim
# per module, with per-test reporting.  Everything absent from it stays on the
# per-module cinder_test_runner.py jobs, so only this one list is needed.
# See Internal/docs/buckified-cpython-tests.md.
'''


def render_dict(name: str, data: dict[str, list[str]]) -> str:
    lines = [f"{name} = {{"]
    for version in sorted(data):
        lines.append(f'    "{version}": [')
        for module in sorted(data[version]):
            lines.append(f'        "{module}",')
        lines.append("    ],")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("inputs", nargs="+", type=Path, help="classifier JSON files")
    parser.add_argument("--cinderx-root", type=Path, required=True)
    args = parser.parse_args()

    tier1: dict[str, list[str]] = {}
    for path in args.inputs:
        payload = json.loads(path.read_text())
        tier1[payload["version"]] = [
            m["module"] for m in payload["modules"] if m["tier"] == 1
        ]

    bzl = args.cinderx_root / "cpython_test_partition.bzl"
    bzl.write_text(BZL_HEADER + "\n" + render_dict("TIER1_TESTS", tier1) + "\n")
    print(f"wrote {bzl}")


if __name__ == "__main__":
    main()
