#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.

"""Generate import shims for Buck-native CPython tests."""

from __future__ import annotations

import argparse
from pathlib import Path

SHIM_TEMPLATE = '''\
# Copyright (c) Meta Platforms, Inc. and affiliates.
# @generated by cinderx/TestScripts/gen_cpython_test_shims.py

"""Run the upstream {module} tests against CinderX."""

import {module} as _module

from cpython_tests._support import load_module_tests


def load_tests(loader, tests, pattern):
    return load_module_tests(loader, _module)
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "pairs",
        nargs="+",
        metavar="MODULE=PATH",
        help="Module to generate, and the output path relative to --output-dir. "
        "The caller supplies the path so the shim layout is defined in one place "
        "-- CPythonTests/defs.bzl, which also declares the genrule's outputs.",
    )
    args = parser.parse_args()

    for pair in args.pairs:
        module, _, relative = pair.partition("=")
        if not module or not relative:
            raise SystemExit(f"expected MODULE=PATH, got {pair!r}")
        output = args.output_dir / relative
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(SHIM_TEMPLATE.format(module=module))


if __name__ == "__main__":
    main()
